### ISSUE TITLE
Updating the table while maintaining the scroll position

### ISSUE THREAD

**Issue by vgoklani** [developerdizzle/react-virtual-list#10]
Hi,

Thanks for taking the time to write this module. 

I'm trying to adapt your list component to my use-case; I'm trying to build a real-time data feed where new messages are prepended to the top of the list. Prepending is easy, I simply rebuild the list in your update function from the test example, and call setState().

But I would also like to maintain the scroll position so the list doesn't jitter while the user is reading. Basically, if the top-most box is currently visible in the viewport, then allow the render function to proceed (because the user is viewing the top of the list). If the user is scrolling somewhere further down the list, then don't render. The problem is I don't know how to check if the first item from the list is currently displayed in the DOM. Is there a way to extract the current set of items being rendered? How do I extract the "key={item.id}" from the rendered boxes?

Thanks!

**Comment by developerdizzle** [comment]
HI @vgoklani - I should be able to update the component to give you the data you need for this.  I'll let you know when I have something.  Thanks for the feedback!

**Comment by developerdizzle** [comment]
@vgoklani, I added a `visibleItems()` method for you.  You can use it in your parent component like this:

```<VirtualList ref="list" ... />```

```var items = this.refs.list.visibleItems();```

The array returned will be the currently visible items (from the `items` property you gave it).  Since you define your own `key` property in `renderItem`, you should have the info you need to find the DOM elements.  Let me know if that solves your problem!

**Comment by developerdizzle** [comment]
Hi @vgoklani - just wanted to see if you had a chance to review this, and if it provided you with what you needed.
