### ISSUE TITLE
Server rendering

### ISSUE THREAD

**Issue by jordansexton** [developerdizzle/react-virtual-list#13]
Right now, `getInitialState` provides an empty array for `state.items` because of [this check](https://github.com/developerdizzle/react-virtual-list/blob/965be5ed8538b1591ab9db2b09c8e4e9e00084f4/src/VirtualList.jsx#L31).

While this makes sense in the context, the component must render twice (once after `componentWillMount` with no items, and then again when the state changes when the calculated height is known on `componentDidMount`). This causes a flash of the empty list beforehand, and also means that server side rendering doesn't work. What do you think of having a property to provide a number of items that will be rendered on the initial render, and then when `componentDidMount` runs, rendered selectively as usual?

This way, it can render enough items to generally fill the screen on the server, the client will render the same items (avoiding a hash mismatch), and then the list will get updated dynamically from that point on. I'm happy to work on a PR if you're interested.

**Comment by quicksnap** [comment]
Thanks for updating your master branch, @jordansexton!

**Comment by jordansexton** [comment]
No problem. If you're using this as a github dependency in your package.json, I recommend binding the link to 30c84374f7b8e6aaa3696cdf0882c97c26c96670 i.e.

```javascript
"react-virtual-list:" "jordansexton/react-virtual-list#30c84374f7b8e6aaa3696cdf0882c97c26c96670"
```

The master branch itself may change since I rely on [a downstream fork of it](https://github.com/stylisted/react-virtual-list) for production use.

**Comment by developerdizzle** [comment]
FYI there is an undocumented `option` in v2 named `initialState` that I am hoping can be used for server-side rendering.  It's currently used for tests https://github.com/developerdizzle/react-virtual-list/blob/master/src/__tests__/VirtualList.js#L118

**Comment by jordansexton** [comment]
SSR works with `firstItemIndex`/`lastItemIndex` now. Thanks!
