### ISSUE TITLE
Handle resizing

### ISSUE THREAD

**Issue by jordansexton** [developerdizzle/react-virtual-list#14]
Right now, `getVirtualState` is called in 4 places: `getInitialState`, `componentWillReceiveProps`, `componentDidMount`, and `onScroll`. If the window is resized, or the orientation changes on mobile, this causes the list to display too few or too many items, depending on the change.

A listener on the window for resize and orientation change events to call `getVirtualState` would fix this (I do this my own wrapper for VirtualList in my application). I can PR if you're interested!

**Comment by developerdizzle** [comment]
Would love a PR for this!

**Comment by developerdizzle** [comment]
Version 2 does this!
