### ISSUE TITLE
Broken on Internet Explorer

### ISSUE THREAD

**Issue by jordansexton** [developerdizzle/react-virtual-list#16]
Tested with IE10 and 11. The issue is [this line](https://github.com/developerdizzle/react-virtual-list/blob/965be5ed8538b1591ab9db2b09c8e4e9e00084f4/src/VirtualList.jsx#L48):
```javascript
var viewTop = typeof container.scrollY !== 'undefined' ? container.scrollY : container.scrollTop;
```

If `container` is `window`, `scrollY` and `scrollTop` are undefined in IE, so `container.pageYOffset` must be used instead.

I'm testing a fix now and will PR.

**Comment by developerdizzle** [comment]
Fixed with the merge of #17
