### ISSUE TITLE
create template

### ISSUE THREAD

**Issue by meisam3322** [developerdizzle/react-virtual-list#20]
hi. thanks to share your project here. I appreciate. 
but how can i create a template for items?

**Comment by developerdizzle** [comment]
Hi @meisam3322, each visible item is rendered with the JSX/markup returned from the `renderItem` property.  There's an example here https://github.com/developerdizzle/react-virtual-list/blob/gh-pages/App.jsx#L39

Hope that answers your question!

**Comment by meisam3322** [comment]
thanks.
