### ISSUE TITLE
Optimize performance of getVirtualItems

### ISSUE THREAD

**Issue by jordansexton** [developerdizzle/react-virtual-list#21]
`getVirtualState` is getting the height of the container every `onScroll` (in addition to a lot of other repeated calculations) when the values likely haven't changed. I believe this is causing elements to be reflowed by the browser, and even if not, is doing the same work over and over.

I will try to optimize the method after #14 which is required to know if things need to be recalculated.

**Comment by jordansexton** [comment]
Also possible related: #1, #3

**Comment by developerdizzle** [comment]
Great catch; this should be able to be cached, as long as we recalculate it on `componentWillReceiveProps` if the container has changed.
