### ISSUE TITLE
Throttle onScroll with requestAnimationFrame

### ISSUE THREAD

**Issue by jordansexton** [developerdizzle/react-virtual-list#22]
Related to #21. Right now, `props.scrollDelay` is used to throttle the internal `onScroll` handler.

The [way I do this in my resize handlers](https://gist.github.com/jordansexton/4216415649aab40d7628) is to use `requestAnimationFrame`. They aren't necessarily mutually exclusive -- `requestAnimationFrame` could be used on the debounced handler. This could improve perceived rendering performance significantly.

Right now the only dependency of the library is React, but I think it could be worthwhile to use [chrisdickinson/raf](https://github.com/chrisdickinson/raf) or another polyfill here.

**Comment by developerdizzle** [comment]
I think this is a great idea.  I would prefer to keep `props.scrollDelay` (for now, at least).  But I'd prefer not to use a polyfill (at least not inside the library itself).  `requestAnimationFrame` has pretty good browser support http://caniuse.com/#feat=requestanimationframe.  Users should still be able to use a polyfill as long as it sets `window.requestAnimationFrame` and mirrors its implementation.

**Comment by developerdizzle** [comment]
Version 2 does this!
