### ISSUE TITLE
Warning: VirtualList(...): React component classes must extend React.Component.

### ISSUE THREAD

**Issue by nite** [developerdizzle/react-virtual-list#30]
The latest version of React (v0.14) throws a warning for react-virtual-list because it doesnt extend React.Component
Same issue as this 
https://github.com/gaearon/redux-devtools/issues/100
Warning: VirtualList(...): React component classes must extend React.Component.

**Comment by Kepro** [comment]
same here :/

**Comment by developerdizzle** [comment]
Upgrading to 0.14 is on my radar!  Unfortunately haven't had a ton of time to work on this project =(

**Comment by manuel-woelker** [comment]
I just took a quick look, and it looks like all that's necessary is to to update the package json to allow the newer react version, preventing clashing React versions. If you want a pull request let me know.

In the future there might be something that could be done with peerDependencies to get better error messages.

**Comment by mrberggg** [comment]
@manuel-woelker Took a quick look and it looks like there's more to it than just updating dependencies. Several deprecated functions in there and `setState` in `componentDidMount`. Don't have time to dig into this now unfortunately.

**Comment by Kepro** [comment]
@developerdizzle can we help you or something? :) i rly need this great tool

**Comment by developerdizzle** [comment]
Well, I am definitely accepting pull requests!  =]  But I will try to get some work done on this over the weekend.  I also want to upgrade it to ES6, probably at the same time.

**Comment by developerdizzle** [comment]
Version 2 now supports React 15
