### ISSUE TITLE
Actual Version not working! old Version is fine

### ISSUE THREAD

**Issue by erik255** [developerdizzle/react-virtual-list#31]
Even the demo (if fresh compiled) does not work. After fixing some obvious bugs i gave up and  used the version from August 22
(010197beb4c6fa208d69847cce8ab7548678cd21) it is the one used in the online-demo I think. 

thanks for your work anyways

**Comment by developerdizzle** [comment]
Crap!  I've been neglecting this project.  I'll fix it.

**Comment by developerdizzle** [comment]
This should be fixed now.  Updated version is `1.7.3`
