### ISSUE TITLE
Example app fails with 1,000,000 items

### ISSUE THREAD

**Issue by quicksnap** [developerdizzle/react-virtual-list#32]
It may be borderline abuse, but I tried the example at http://developerdizzle.github.io/react-virtual-list/ with a million items, and it fails to render when I drag the scrollbar to the bottom. Know what would cause the failure?

We have a requirement to virtually scroll millions of items, so I could potentially help to write an improvement.

Latest Chrome on OSX.

**Comment by quicksnap** [comment]
On Safari it also freaks out..

**Comment by quicksnap** [comment]
Could it be that the empty container is simply too large? Would it help if the height were capped, and the vertical scrolling were to map logarithmically to the index position?

**Comment by developerdizzle** [comment]
Hmm, great question.  It may have to do with browsers' maximum height limitation.  I'll run some tests when I get a chance, but I suspect there will be a point where the page is just too high.  Logarithmic mapping is an interesting proposal though.

**Comment by quicksnap** [comment]
Running a few tests, it's very much a limitation of either the height or the padding. Most likely, something getting converted into a floating point or simply capping out. Either way, it produces madness =)

Right now, I'm working off a @jordansexton's master branch, as it resolves server-rendering issues. I'll be experimenting with a maximum height and linear scaled scrolling for now.

**Comment by jordansexton** [comment]
I don't have much to say on this as I never render more than 50 rows on a page right now in my application. I use this library because the individual rows are quite expensive to render (50 DOM elements per row with 4-6 responsive images, some @2x res), but I've never tested it academically with a massive amount of rows.

**Comment by developerdizzle** [comment]
I'm convinced this is a result of each browsers' maximum height limitation.  Closing this, but feel free to re-open if anyone believes otherwise.
