### ISSUE TITLE
React v15 support

### ISSUE THREAD

**Issue by gajus** [developerdizzle/react-virtual-list#35]
`getDOMNode` has been removed in v15, https://facebook.github.io/react/blog/2016/04/07/react-v15.html.

It is used in several places in code, e.g. https://github.com/developerdizzle/react-virtual-list/blob/f7c96fe904728269e4b7e2114e2d004b2cc22a48/src/VirtualList.jsx#L78.

**Comment by bobmclaren** [comment]
I'm new to this, so perhaps I'm doing something wrong, but when I tried using this pakage in my React v15 app, I received the "Something is calling a React component directly. Use a factory or JSX instead. See: https://fb.me/react-legacyfactory" error.

**Comment by sc0ttyd** [comment]
:bump:

**Comment by developerdizzle** [comment]
Version 2 now supports React 15
