### ISSUE TITLE
React 15.5 support

### ISSUE THREAD

**Issue by arslivinski** [developerdizzle/react-virtual-list#53]
React 15.5 introduced another warnings, like using React.PropTypes (https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html).

It's needed to fix these warnings.

**Comment by haxxxton** [comment]
@developerdizzle bumping

**Comment by developerdizzle** [comment]
Thanks to @haxxxton v `2.2.1` now supports this!

**Comment by haxxxton** [comment]
@developerdizzle, would you mind adding a `release` tag to v2.2.1 on github please
