### ISSUE TITLE
Documentation/Feature Request

### ISSUE THREAD

**Issue by ClickSimply** [developerdizzle/react-virtual-list#56]
Pulled out my hair over this for more than an hour.

The container of the list MUST have "box-sizing: border-box;" set, or the padding will contribute to the container's height and the whole thing breaks down.

Would be nice if the lib injected this style or you mentioned it in the documentation. :)

If it helps my implementation looks like this:
```js
this.list = VirtualList()(({
    virtual,
    itemHeight,
}) => (
    <div style={{boxSizing: "border-box", ...virtual.style}}>
        {virtual.items.map((prod, idx) => (
            <div style={{height: itemHeight}} key={idx}>{new MenuItem(prod, this.state.menu.catTypes[prod.mainCategory as string], this.state.menu.locationOrdering).render()}</div>
        ))}
    </div>
));

```

**Comment by ClickSimply** [comment]
Thank you!

**Comment by DGizmo** [comment]
Man, that's crazy! Long puzzled what is wrong with my implementation. 
It MUST be in the docs!

**Comment by developerdizzle** [comment]
I've added this to the default styles https://github.com/developerdizzle/react-virtual-list/blob/master/src/utils/defaultMapVirtualToProps.js#L20
