### ISSUE TITLE
Support cordova/phonegap

### ISSUE THREAD

**Issue by studentIvan** [developerdizzle/react-virtual-list#67]
Scroll event does fire in the cordova only on the scroll process stopped.
Here is the article about this stuff https://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal/

Does it possible to add the support for cordova using some other stuff/options? (maybe not to use the scroll event for cordova, maybe even setInterval instead - just to make it working after all)

**Comment by studentIvan** [comment]
While testing I checked that getVisibleItemBounds function returns incorrect data before the scroll will be stopped. Seems the element.offsetTop does not update.

**Comment by developerdizzle** [comment]
Hi @studentIvan !  Unfortunately I know nothing about Cordova/PhoneGap, but if you're able to submit a PR I will happily review it.
