### ISSUE TITLE
React 16 Support

### ISSUE THREAD

**Issue by 0xcaff** [developerdizzle/react-virtual-list#71]
Currently, the highest supported version is react 15.

https://github.com/developerdizzle/react-virtual-list/blob/42dbd7d83835a381918fe169f1f421c60b88d1f7/package.json#L53-L56

**Comment by webyonet** [comment]
+1

**Comment by marher86** [comment]
+1

**Comment by AnastasiaBuniak** [comment]
+1

**Comment by mrchief** [comment]
Are you open to PRs on this and #62? I need it for my own component (you can read the referenced issue for details).
